app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix: app

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: app

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: app/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: app/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: app/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: app/profile

isoftbet_dashboard:
     path:     app/dashboard
     defaults: { _controller: AppBundle:Dashboard:index }
