# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER: ~
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                # csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:
                path: /app/logout        
            anonymous:    true

    access_control:
        - { path: ^app/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^app/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^app/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^app/admin/, role: ROLE_ADMIN }
        - { path: ^app/dashboard$, role: ROLE_USER }
