# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    #oauth_user_provider.class: LinkAndLearn\Bundle\Security\Core\User\FOSUBUserProvider
    account.security_listener.class: AppBundle\Security\Listener\SecurityListener
    #comment.sorting.class: LinkAndLearn\Bundle\Sorting\CommentOrderSorting
    #comment.sort.order: 'DESC'

services:
  account.security_listener:
        class: "%account.security_listener.class%"
        arguments: ['@security.context', '@session', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
