AppBundle\Entity\Customer:
    type: entity
    table: customer
    repositoryClass: AppBundle\Entity\CustomerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        cnp:
            type: integer
            length: 11
        name:
            type: string
            length: '256'

        createdAt:
            type: datetime
        updatedAt:
            type: datetime
    lifecycleCallbacks: {  }
