AppBundle\Entity\Customer:
    type: entity
    table: customer
    repositoryClass: AppBundle\Entity\CustomerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        cnp:
            type: string
            length: 256
        name:
            type: string
            length: '256'
        balance:
            type: decimal
            precision: 15
            scale: 2
        createdAt:
            type: datetime
            nullable: true
        updatedAt:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
