AppBundle\Entity\Transaction:
    type: entity
    table: transaction
    repositoryClass: AppBundle\Entity\TransactionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        amount:
            type: decimal
            precision: 15
            scale: 2
        type:
            type: string
            length: 100
            column: transaction_type
        createdAt:
            type: datetime
            nullable: true
        updatedAt:
            type: datetime
            nullable: true
    manyToOne:
        customer:
            targetEntity: AppBundle\Entity\Customer
            inversedBy: transaction
            joinColumn:
                column: customer_id
    lifecycleCallbacks: {  }
